#!/usr/bin/env node
// Renders .env (DockFlare) + docker-compose.omniroute.yml from config.json.
// Zero dependencies. Node 18+.
import { readFileSync, writeFileSync } from 'node:fs';

const cfgPath = process.env.CONFIG_FILE || 'config.json';
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'));
const cf = cfg.cloudflare || {};
const omni = cfg.omniroute || {};

const required = {
  'cloudflare.apiToken': cf.apiToken,
  'cloudflare.accountId': cf.accountId,
  'cloudflare.zoneId': cf.zoneId,
  'cloudflare.baseDomain': cf.baseDomain,
};
for (const [k, v] of Object.entries(required)) {
  if (!v) {
    console.error(`Missing required config: ${k}`);
    process.exit(1);
  }
}

const base = String(cf.baseDomain).trim();
const flavor = String(omni.flavor || 'base').toLowerCase();
const versions = Array.isArray(omni.versions) && omni.versions.length ? omni.versions : ['latest'];
const extraEnv = omni.env || {};

// --- .env for the DockFlare control plane ---
const envLines = [
  `CF_API_TOKEN=${cf.apiToken}`,
  `CF_ACCOUNT_ID=${cf.accountId}`,
  `CF_ZONE_ID=${cf.zoneId}`,
  `TUNNEL_NAME=${cf.tunnelName || 'dockflare-omniroute'}`,
  `CLOUDFLARED_NETWORK_NAME=cloudflare-net`,
  `SCAN_ALL_NETWORKS=true`,
];
writeFileSync('.env', envLines.join('\n') + '\n');

// --- helpers ---
const slug = (v) =>
  v === 'latest'
    ? 'latest'
    : 'v' + String(v).replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '');
const imageTag = (v) => (flavor === 'web' ? `${v}-web` : `${v}`);

// --- OmniRoute compose overlay ---
let servicesYaml = '';
for (const v of versions) {
  const s = slug(v);
  const name = `omniroute-${s}`;
  const host = `${s}.${base}`;
  const custom = Object.entries(extraEnv)
    .filter(([, val]) => val !== '' && val != null)
    .map(([k, val]) => `      - ${k}=${val}`);
  servicesYaml +=
    `\n  ${name}:\n` +
    `    image: diegosouzapw/omniroute:${imageTag(v)}\n` +
    `    container_name: ${name}\n` +
    `    restart: unless-stopped\n` +
    `    stop_grace_period: 40s\n` +
    `    volumes:\n` +
    `      - ${name}-data:/app/data\n` +
    `    environment:\n` +
    `      - PORT=20128\n` +
    `      - NEXT_PUBLIC_BASE_URL=https://${host}\n` +
    (custom.length ? custom.join('\n') + '\n' : '') +
    `    labels:\n` +
    `      - dockflare.enable=true\n` +
    `      - dockflare.hostname=${host}\n` +
    `      - dockflare.service=http://${name}:20128\n` +
    `    networks:\n` +
    `      - cloudflare-net\n` +
    `    healthcheck:\n` +
    `      test: ["CMD", "node", "healthcheck.mjs"]\n` +
    `      interval: 30s\n` +
    `      timeout: 5s\n` +
    `      retries: 3\n` +
    `      start_period: 20s\n`;
}

const volumesYaml = versions.map((v) => `  omniroute-${slug(v)}-data:`).join('\n');

const compose =
  `# AUTO-GENERATED by scripts/render.mjs — do not edit by hand.\n` +
  `services:${servicesYaml}\n` +
  `volumes:\n${volumesYaml}\n\n` +
  `networks:\n` +
  `  cloudflare-net:\n` +
  `    name: cloudflare-net\n` +
  `    external: true\n`;
writeFileSync('docker-compose.omniroute.yml', compose);

console.log(`Rendered .env + docker-compose.omniroute.yml`);
for (const v of versions) {
  console.log(`  https://${slug(v)}.${base}  ->  diegosouzapw/omniroute:${imageTag(v)}`);
}
